<<<<<<< HEAD
# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: dbyll
google_analytics: dbyll
title: dbyll

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: dbyll

description: Stylish Jekyll Theme
title: dbyll
disqus: dbyll-ghost # disqus short name
author:
  name: dbyll
  email: junghyun.jung@usc.edu
  github: junghyunJJ
  twitter: junghyunjj
  pinterest: junghyunjj
  linkedin: junghyunjj
  bio: Hi I'm JJ!
  email_md5: 726351295ec82e145928582f595aa3aa

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

plugins:
  - jekyll-paginate
=======
theme: jekyll-theme-minimal
>>>>>>> 7400aaad578def5dda85ab9bdf8451f4c7012e13
